server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        #是否注册
        register: true
        #健康检查路径
        health-check-path: /actuator/health
        #健康检查时间间隔
        health-check-interval: 15s
        #开启IP地址注册
        prefer-ip-address: true
