server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    #    网关配置
    gateway:
      routes:
        - id: payment_routh                   #路由ID，没有固定规则要求唯一，简历配置服务名使用
          uri: http://localhost        #匹配后提供服务的路由地址
          predicates:
            - Path=/openfeign/consumer/order/get/**   #断言，路径相匹配的进行路由
        - id: payment_routh2
          uri: http://localhost
          predicates:
            - Path=/openfeign/consumer/order/getTimeout/**

#  spring  cloud 相关配置
eureka:
  instance:
    # 在注册中心的实例名字
    instance-id: gateway9827
    # 访问路径可以现实IP地址
    prefer-ip-address: true
    # 向注册中心发送心跳的间隔
    lease-renewal-interval-in-seconds: 30
    # 如果2秒没有获取到心跳则从注册中心删除
    lease-expiration-duration-in-seconds: 90
  client:
    #表示是否将自己注册进Eureka Server默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #向EurekaServer中注册
    service-url:
      defaultZone: http://eureka7001.local:7001/eureka,http://eureka7002.local:7002/eureka
