server:
  port: 80
spring:
  application:
    name: zookeeper-consumer-order
  cloud:
    zookeeper:
      # 注册中心地址
      connect-string: 127.0.0.1:2181
      # 会话超时时间
      session-timeout: 5000
      # 链接超时时间
      connection-timeout: 5000
      # 最大重试次数
      max-retries: 5

