server:
  port: 7002

eureka:
  instance:
    hostname: eureka_node2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.local:7001/eureka/
