server:
  port: 7001

eureka:
  instance:
    hostname: eureka-server-7001
  client:
    # 是否将自己注册到注册中心
    register-with-eureka: false
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: false
    service-url:
      defaultZone: http://rureka7002.local:7002/eureka/
  server:
    # 关闭Eureka Server保护机制
    enable-self-preservation: false
    # 配置心跳间隔时间为2秒
    eviction-interval-timer-in-ms: 2000


