server:
  port: 3344

spring:
  application:
    name: config-core3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaojiebin/spring-cloud-learn-02.git
          search-paths:
            - spring-cloud-learn-02/cloud-netflix/config-file
          username: 543033627@qq.com
          password: aloneman_0629
      label: master

#  spring  cloud eureka 相关配置
eureka:
  instance:
    # 在注册中心的实例名字
    instance-id: config-core3344
    # 访问路径可以现实IP地址
    prefer-ip-address: true
    # 向注册中心发送心跳的间隔
    lease-renewal-interval-in-seconds: 30
    # 如果2秒没有获取到心跳则从注册中心删除
    lease-expiration-duration-in-seconds: 90
  client:
    #表示是否将自己注册进Eureka Server默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #向EurekaServer中注册
    service-url:
      defaultZone: http://eureka7001.local:7001/eureka,http://eureka7002.local:7002/eureka


