server:
  port: 8001

spring:
  application:
    name: provider-stock
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 4ab8c1bb-28a2-46cc-9043-e269cf2afbf6
        group: stock-group
        password: nacos
        username: nacos
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.ip}:3306/seata_stock?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectionCollation=utf8mb4_general_ci&uerSSL=false
    username: root
    password: xiaojiebin
  jackson:
    default-property-inclusion: non_null
database:
  ip: localhost


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: stock_tx_group
  service:
    vgroup-mapping:
      stock-tx-group: shenzhen-cluster
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 4ab8c1bb-28a2-46cc-9043-e269cf2afbf6
      group: SEATA_GROUP
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      # 这里必须和seata-server配置的名字一样
      application: customize-seata-server
      # 必须和seata-server在同一个命名空间
      namespace: 4ab8c1bb-28a2-46cc-9043-e269cf2afbf6
      # 必须和seata-server在同一个分组中
      group: seata-group
      cluster: shenzhen-cluster




