server:
  port: 5003
spring:
  application:
    name: commodity-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: 4ab8c1bb-28a2-46cc-9043-e269cf2afbf6
        group: commodity-group
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.ip}:3306/stock?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectionCollation=utf8mb4_general_ci&uerSSL=false
    username: root
    password: xiaojiebin
  jackson:
    default-property-inclusion: non_null

seata:
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      namespace: 4ab8c1bb-28a2-46cc-9043-e269cf2afbf6
      group: SEATA_GROUP
      dataId: "seataServer.properties"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 4ab8c1bb-28a2-46cc-9043-e269cf2afbf6
      username: nacos
      password: nacos