spring:
  application:
    name: hystrix-consumer-order-80
server:
  port: 80

#  spring  cloud 相关配置
eureka:
  instance:
    instance-id: hystrix-openfeign-order80
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.local:7001/eureka,http://eureka7002.local:7002/eureka

# openfeign相关配置
feign:
  client:
    config:
      default:
        # 请求超时时间
        read-timeout: 10000
        # 链接超时时间
        connect-timeout: 10000
  # 新版本开启openfeign 的服务降级
  circuitbreaker:
    enabled: true


# open-feign日志增强
logging:
  level:
    com.xiao.cloud.cloudeurekaopenfeignconsumerorder80.service.PaymentService: debug